### ISSUE TITLE
Получать данные о сериале

### ISSUE THREAD

**Issue by felixx69** [comov/bystar_bot#1]
Откройте ссылку
https://animego.org/anime/mastera-mecha-onlayn-alisizaciya-voyna-v-podmire-2-1464

после открытия страницы, js подгружает плеер и выводит информацию о сериале.

Вам нужно научиться получать эту информацию и выводить в консоль. Пример:
![image](https://user-images.githubusercontent.com/15646544/88661573-86314a00-d0fa-11ea-94c0-322646ed9727.png)

**Comment by aastashov** [comment]
Попробуйте использовать эту библиотеку
https://pypi.org/project/beautifulsoup4/
